
# paste config here
language: java

jdk:
 - oraclejdk8

sudo: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start





